#!/bin/bash

clear
echo -e "================================================="
echo -e "#                 HALUBOY                       #"
echo -e "#-----------------------------------------------#"
echo -e "# For Debian 9 & Debian 10 64 bit               #"
echo -e "# For Ubuntu 18.04 & Ubuntu 20.04 64 bit        #"
echo -e "# For VPS with KVM and VMWare virtualization    #"
echo -e "# Build Up By HALUBOYS                             #"
echo -e "#-----------------------------------------------#"
echo -e "# Thanks To                                     #"
echo -e "#-----------------------------------------------#"
echo -e "# HALLUBOY                                      #"
echo -e "# ALLAH S.W.T                                   #"
echo -e "# My Family                                     #"
echo -e "# Google                                        #"
echo -e "#                                               #"
echo -e "# XZVNCT.MY.ID                                  #"
echo -e "#                                               #"
echo -e "#-----------------------------------------------#"
echo -e "                   BITCH                        #"
echo -e "================================================="
